#ifndef MAIN_SCREEN_H
#define MAIN_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// The create function generated by LVGL Pro
lv_obj_t * main_screen_create(void);

#ifdef __cplusplus
}
#endif

#endif // MAIN_SCREEN_H
